server:
  port: 9292

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exception_db
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


